server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

management:
  server:
    port: 9090

# For Prod
# springfox:
#   documentation:
#     enabled: false
